version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: legion-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  legion-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: legion-server
    restart: always
    ports:
      - "3001:3001"
    environment:
      - RUST_LOG=info
      - LEGION_DATA_PATH=/data
      - REDIS_URL=redis://redis:6379
    volumes:
      - legion-data:/data
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: legion-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./wasm-client:/usr/share/nginx/html:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - legion-server

volumes:
  redis-data:
  legion-data:
