# Add these dependencies to Cargo.toml for Nova integration

[dependencies]
# Production Nova implementation
nova-snark = { version = "0.32.0", default-features = false, features = ["asm", "parallel"] }
bellperson = { version = "0.28.0", default-features = false }

# Existing dependencies (keep these)
halo2_proofs = "0.3"
pasta_curves = "0.6.0"
ff = "0.13.0"
rand = "0.8.5"
serde = "1.0.197"
bincode = "1.3.3"
anyhow = "1.0.82"
blake3 = "1.5"

# ... rest of your existing dependencies