[build]
rustflags = ["-A", "unexpected_cfgs", "-A", "unused_imports", "-A", "unused_variables", "-A", "dead_code", "-A", "deprecated"]

[target.'cfg(all())']
rustflags = ["-A", "clippy::too_many_arguments", "-A", "clippy::type_complexity", "-A", "clippy::needless_range_loop"]
